import esbuild from "esbuild";
import process from "node:process";
import { appendFile, readFile, readdir } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "@codemirror/state", "@codemirror/commands"],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  metafile: true,
});

if (prod) {
  const result = await context.rebuild();
  await context.dispose();
  const packages = new Set(Object.keys(result.metafile.inputs).filter((path) => path.startsWith("node_modules/"))
    .map((path) => path.split("/").slice(1, path.startsWith("node_modules/@") ? 3 : 2).join("/")));
  const notices = await Promise.all([...packages].sort().map(async (name) => {
    const directory = `node_modules/${name}`;
    const file = (await readdir(directory)).find((entry) => /^license(?:\.md|\.txt)?$/i.test(entry));
    if (!file) throw new Error(`Missing bundled dependency license: ${name}`);
    return `${name}\n${await readFile(`${directory}/${file}`, "utf8")}`;
  }));
  await appendFile("main.js", `\n/* Bundled third-party licenses\n\n${notices.join("\n\n").replace(/\*\//g, "* /")}\n*/\n`);
} else {
  await context.watch();
}
